### ISSUE TITLE
请问上传图片可以先压缩再传给后台吗？

### ISSUE THREAD

**Issue by leeycode** [waynecz/vue-img-inputer#10]
现在手机拍的照片都很大一张，估计4-5M，上传很慢，影响客户体验，能不能压缩一下图片后提交

**Comment by waynecz** [comment]
@leeycode 😂之前看到的时候在外面，回家忘记回了，压缩可以有，不过本来的想法是在业务代码里面按需自己写。
我尽快加上这个功能吧。

ps：自己写的话，用 [canvas](http://leonshi.com/2015/10/31/html5-canvas-image-compress-crop/) 其实代码挺简单的，但是要做到很健全个平台兼容的前端压缩方案，我贴个库：[https://github.com/think2011/localResizeIMG](https://github.com/think2011/localResizeIMG)，希望有帮助
