### ISSUE TITLE
iphone6 plus 上 点击上传完老是自动刷新页面

### ISSUE THREAD

**Issue by maplehsu** [waynecz/vue-img-inputer#11]
我选择一个图片上传 拍照完经常会自动刷新一下页面 是什么情况

**Comment by waynecz** [comment]
可以贴一下关键代码吗，以及系统版本和浏览器的信息

**Comment by maplehsu** [comment]
![image](https://user-images.githubusercontent.com/4917754/27281144-28042c92-551d-11e7-86a4-9ccc50473d4d.png)

微信内置浏览器

微信版本 。6.5.8
