### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by evan2579429110** [waynecz/vue-img-inputer#15]
为什么刚开始使用还可以，过了一两天以后单击等选择图片弹出要隔四五秒，有时候达到七八秒？

**Comment by waynecz** [comment]
请问你的 `accept` 属性的值有特别指定吗？类似于 `image/jpg,image/png`  这样

**Comment by evan2579429110** [comment]
你好，难倒是因为 accept="image/*"，这样吗？我改成了每个image都写出来了，的确感觉快了，但我还要经过测试才能发表最后言论，谢谢！

**Comment by waynecz** [comment]
嗯嗯，当 image 为*时，的确会很慢！

**Comment by evan2579429110** [comment]
经过测试，发现的确是没有明确标明image的类型的原因，谢谢！
