### ISSUE TITLE
初始图片

### ISSUE THREAD

**Issue by WindStormrage** [waynecz/vue-img-inputer#19]
请问插件的初始图片怎么设置，是不是用imgSrc设置，为什么我设置了显示不出来

![image](https://user-images.githubusercontent.com/25522284/27731694-b11fbaa4-5dc0-11e7-8ec2-c0fa4afa71f3.png)

变成了这样子

![image](https://user-images.githubusercontent.com/25522284/27731764-f815ff9a-5dc0-11e7-9cdd-1dc4e89fcf68.png)

我图片地址是没问题的

**Comment by waynecz** [comment]
这里 webpack 设置了 publicPath 吗？

**Comment by WindStormrage** [comment]
我是新手，webpack 的配置我没动过，请问是要改哪里呀，，
还有我的其他地方的图片用这个位置是可以显示的呀？

**Comment by nevermind123456** [comment]
你这个是因为imgSrc前面没有加冒号吧~

**Comment by liaohainan** [comment]
这个图片路径是挺头疼的，我建议实在搞不定就import引入进来，用一个变量去接收，然后绑定到这个组件的imgSrc就不会出问题了
