### ISSUE TITLE
源文件vue中多了一个template

### ISSUE THREAD

**Issue by zhouyuexie** [waynecz/vue-img-inputer#2]
```html
<template></template>
```

在最后一行,没见过这种写法....很奇怪

**Comment by waynecz** [comment]
@zhouyuexie 是我蠢了😂，谢谢指出！

**Comment by zhouyuexie** [comment]
@waynecz 我是来学习滴,顺便问一个问题,我自己编译的vue源文件可以直接使用,但是发布到npm后再引用vue直接报错,不明白是不是我哪里出了问题...

[项目地址](https://github.com/zhouyuexie/vue-input-code)

现在还无法引用,别安装...

**Comment by waynecz** [comment]
@zhouyuexie 试了一上午没试出所以然来 Or2
你试着

+ 把`<template type="x/template">`去掉`type`属性
+ `<script>`改成`<script type="text/ecmascript-6">`
+ 组件加个`name`属性
+ `vue-html-loader`降到`1.0.0`

然后打包再发布到npm上引一下试试？

**Comment by zhouyuexie** [comment]
我换了另一种方式引用:

1. 一般是可以自己编译好成js发布别人直接引用.
2. 也可以直接引用发布的vue文件,只是用之前需要编译.

第二种方式无法直接网页上调用,不过能看到你的包应该也不会不知道这个的需要编译的吧.

**Comment by waynecz** [comment]
@zhouyuexie 恩，你说的第二点，我直接引用你的vue文件也是可以的，而且现在一般写vue都有自己的打包编译流程也是出不了什么错。

但说实话奇怪的是为什么第一点的那种方式到你那不行了。。我觉得你可以试一下用`vue-img-inputer`这个仓库壳子来打包出你的js然后发布到npm上测试下是不是构建问题

**Comment by zhouyuexie** [comment]
@waynecz 我试过你的webpack配置,然后将output的文件复制到我本地覆盖后一样报错.....

不想折腾了,老老实实的编译吧😂

**Comment by waynecz** [comment]
@zhouyuexie 😢如果以后灵机一动突然解决了急的来挖下坟告诉我下哈哈哈哈

**Comment by zhouyuexie** [comment]
@waynecz 那是必须的😝

**Comment by LNdoremi** [comment]
您好！我觉得这个插件非常好用。我现在遇到一个问题：onChange这个函数怎么用？

**Comment by waynecz** [comment]
@LNdoremi 
```vue
<script>
...
methods: {
    handleFileChange (file) {
        // do something with file
    }
}
...
<script>

<VueImgInputer :onChange="handleFileChange"/>
```

就是当做个prop然后传入个回调函数使用，这样写可以解决你的疑惑吗？

**Comment by LNdoremi** [comment]
感谢您的回复，问题已解决~

**Comment by LNdoremi** [comment]
您好，我又来了。。我这边在电脑谷歌浏览器上面测试没有问题，但是在手机微信网页中使用时，选择了图片无法渲染出来，请问您知道是什么原因吗？

**Comment by waynecz** [comment]
@LNdoremi 可以看下组件里你写的代码，以及访问的微信版本和系统吗？

**Comment by LNdoremi** [comment]
![vue-img-inputer](https://cloud.githubusercontent.com/assets/12825908/24535266/8cf7a216-1605-11e7-8f2a-9184cf93f03b.png)
安卓系统4.4.2，微信版本6.5.7
谢谢您的及时回复~

**Comment by LNdoremi** [comment]
测试地址：http://139.196.40.167:8080/#/matchInfo
图片上传在第三页，可以的话帮忙看看~
谢谢~

**Comment by Mr-ou** [comment]
@waynecz 
methods: {
    handleFileChange (file) {
        console.log(JSON.stringify(file))
    }
}
测试了很多次，打印出来的file都是一个空对象。如何才能获取到图片数据，上传给服务器。
