### ISSUE TITLE
当imgSrc为动态数据时，页面不渲染

### ISSUE THREAD

**Issue by tyf221578** [waynecz/vue-img-inputer#22]
如题，当传入的参数 :imgSrc="item.list_image" 时，item.list_image是ajax返回的数据，页面只渲染了组件，组件内的图片，并没有渲染，请问这个问题怎么解决比较好呢？

我尝试了一下加一个v-if的判断：
<imgInputer v-if="item.list_image" v-model="file" accept="image/*" :imgSrc="item.list_image" @onChange="fileChange"></imgInputer>
这样是可行的，这样整个组件会等待ajax返回后再渲染，请问还有更优雅一点的方式吗？

**Comment by waynecz** [comment]
嗯！非常好棒的建议！我去修改下支持这种操作

**Comment by tyf221578** [comment]
不好意思，确认过了，是我这边的问题，您的这个组件是没有问题的，感谢您的回复。
