### ISSUE TITLE
图片回填后如何清除

### ISSUE THREAD

**Issue by coco128** [waynecz/vue-img-inputer#23]
怎么清空回填后图片的路径？

**Comment by waynecz** [comment]
imgSrc 如果为空的话自动会清除的

**Comment by coco128** [comment]
可能是我写的代码有问题 给他赋值为空也 没有清空

**Comment by coco128** [comment]
再请教一个问题  我发现iview的模态框和您这组件有样式冲突

**Comment by coco128** [comment]
![rfa6j6pg f zse f kzh r](https://user-images.githubusercontent.com/28700133/29102783-0a1f52a8-7cee-11e7-98c0-0b46a5893cff.png)这种组件的过度效果冲突有什么办法解决么，求教

**Comment by waynecz** [comment]
@coco128 样式冲突的问题具体是指哪个样式吗？，我看着给 scope 一下

**Comment by waynecz** [comment]
我发个新版，把样式问题都解决下，稍等

**Comment by waynecz** [comment]
@coco128 新版本 1.1.1 修复了这些问题，你看看

**Comment by coco128** [comment]
问题解决了，谢谢waynecz大大

**Comment by waynecz** [comment]
😀不用不用，这是个问题还好你发现了

**Comment by nevermind123456** [comment]
图片回填清空解决了吗？请问怎么解决的呢

**Comment by nevermind123456** [comment]
imgSrc 如果为空为什么也没有清空图片呢？

**Comment by liaohainan** [comment]
我也发现这个问题，没有reset功能，我还是加了ref，手动给置空的
that.$refs.uploadInput.dataUrl = ''
that.$refs.uploadInput.fileName = ''
