### ISSUE TITLE
如何主动触发点击事件？

### ISSUE THREAD

**Issue by tinymins** [waynecz/vue-img-inputer#25]
有一个页面，希望在快捷入口进入时，不需要用户点击上传按钮就打开上传框。

意思就是这个页面加载的时候，就主动触发一次组件的`click`事件，要如何做？

```es
  mounted() {
    if (this.$route.params.pickImage) {
      this.$refs.$image.$el.click();
    }
  },
```
现在这样 并不行

**Comment by waynecz** [comment]
得选择到组件内部的 `file input`

```vue
<vue-img-inputer ref="image" />

...
mounted() {
    this.$refs.$image.$el.querySelector('[type=file]').click();
}
...

```

**Comment by tinymins** [comment]
可以，稳了，感谢！

**Comment by tinymins** [comment]
https://dev.haimanchajian.com/m/secret/post 为什么直接打开了相机？iPhone6s plus

**Comment by waynecz** [comment]
这个现在有点坑，暂时还没找到填的办法，因为 capture 的原因😂，你可以先这样写

```
// 针对 ios
<vue-img-inputer accept="xxxx; capture= capture" />

// 针对 android 正常用即可
<vue-img-inputer accept="xxxx" />

```

这里两种系统都需要「既可以选择相册又可以拍摄照片」 的话需要根据 UA `v-if`。。。。

**Comment by tinymins** [comment]
还有
1. 能不能自定义四周的`border-radius`？我这里的组件都是没有圆角的设计，上传有个`5px`的圆角有点奇怪。
2. 我的`px2rem`为什么没有处理到`VueImgInpute`r的`css`？审查元素可以看到控件的宽度单位还是`px`

**Comment by waynecz** [comment]
因为组件内 css 是 in JS 的，所以处理不到，你需要手动去覆盖

```css
.img-inputer {
    border-radius: 0;
}
```

**Comment by tinymins** [comment]
@waynecz 看完了你的源码，有点小疑问就是`resetInput`函数的作用是什么？
