### ISSUE TITLE
图片设置maxSize的时候报错信息被遮挡

### ISSUE THREAD

**Issue by liaohainan** [waynecz/vue-img-inputer#26]
我给组件设置样式为宽高各60，我看源码给的错误提示是width是100%，但是提示文字超过了60px，被组件遮挡住了一部分，麻烦看一下

而且我想重置内部的样式只能通过改源码，而没办法自定义

**Comment by waynecz** [comment]
回复晚了不好意思，可以看下你的设置和代码吗

**Comment by Mcqueengit** [comment]
@waynecz  你好，我想将样式设置成60*60的大小，效果如图
![image](https://user-images.githubusercontent.com/23163376/29872723-5765cc5a-8dc3-11e7-9df1-799f955b13c4.png)
我看到大小的可以通过size来设置，但是并不能达到我想要的结果，另外看到这一句话
![image](https://user-images.githubusercontent.com/23163376/29872807-ad8c52a2-8dc3-11e7-986d-80bc11cd00e4.png)
不是特别懂，是可以通过BEM来设置大小吗，因为是新手，希望能给予解释，谢谢

**Comment by liaohainan** [comment]
就只是给了个宽高，因为您组件内给了scoped，所以内部的样式都无法更改
width:60px; height:60px;

**Comment by waynecz** [comment]
@liaohainan 新版本去除了scoped ，版本`1.1.4`

**Comment by liaohainan** [comment]
谢谢
