### ISSUE TITLE
如何设置界面的大小

### ISSUE THREAD

**Issue by Mcqueengit** [waynecz/vue-img-inputer#27]
大神你好，正如我在另一个问题提到的一样，我想实现如图所示的效果
![image](https://user-images.githubusercontent.com/23163376/29906406-485223ec-8e47-11e7-842f-4efc1a50a44a.png)

即图片大小是60*60，图片下方是使用你的组件实现的，但是我发现只能通过 size设置small 、normal和large，能否自定义大小呢？谢谢

**Comment by waynecz** [comment]
首先自己传一个随意的 size 进去，例如：square
```
<vue-img-inputer size="square"/>
```

然后定义这么条 css
```css
```

**Comment by Mcqueengit** [comment]
谢谢，我发现了一个问题还有一个疑问。
问题，如果我在accept中进行设置如下，
![image](https://user-images.githubusercontent.com/23163376/29910965-a71b1458-8e5e-11e7-8b4e-984e780034cb.png)
在电脑端打开是找不到图片，如下
![image](https://user-images.githubusercontent.com/23163376/29910984-c273d99c-8e5e-11e7-8f62-78c053bcc5f8.png)
但是通过你的[demo](http://waynecz.github.io/VueImgInputer/index.html)或者用手机端就可以看到图片，电脑用的浏览器是chrome，手机是小米（且手机上传照片后会旋转90度）
![image](https://user-images.githubusercontent.com/23163376/29911098-351def1e-8e5f-11e7-9353-2ea2866a46c8.png)

疑问，我是通过npm install vue-img-inputer -D安装，安装后在webpack的node_modules找到了vue-img-inputer文件夹，我猜想如图所示的文件应该就是我在使用webpack时引入的组件，但是我将main.css中的css修改后，即便重新npm install 、npm run dev，但是样式还是没有修改（即修改组件的样式，但是样式没有变），这是怎么回事
![image](https://user-images.githubusercontent.com/23163376/29911382-457e74cc-8e60-11e7-9b20-b70f19749baa.png)

**Comment by waynecz** [comment]
1. 用双引号试试？

2. 图片旋转可以简单的[看下这个](https://juejin.im/post/595599e75188250d99181801)


3. 最后一个是因为默认引入的是打包好的 `dist/vueImgInputer.js`

你可以这样写

```vue
import vueImgInputer from 'vue-img-inputer/src/component/imgInputer.vue'
```

来实现引入元组件

**Comment by Mcqueengit** [comment]
双引号也不可以

**Comment by Mcqueengit** [comment]
我找到解决方法了，只要将accept设置为"image/gif,image/jpeg,image/jpg,image/png"，和单引号双引号没有关系，重点是image/jpeg
