### ISSUE TITLE
获取不到文件数据啊

### ISSUE THREAD

**Issue by James-jun06** [waynecz/vue-img-inputer#29]
我使用这个组件上传，如下

![qq 20170911161753](https://user-images.githubusercontent.com/21353800/30264937-28b70b00-970d-11e7-8ce0-60b07eb4cbd3.jpg)

`data() {
	    	return {
	    		corpInfo:{
	    			logo:'',
	    		},
	    		uploadFileData:null,`

但是获取到的文件数据（uploadFileData）是空啊{}

**Comment by waynecz** [comment]
诶？代码能再详尽点吗
