### ISSUE TITLE
选中图片后，立即上传给后台

### ISSUE THREAD

**Issue by leeycode** [waynecz/vue-img-inputer#30]
您好，请问此插件可以完成以上功能吗？感谢

**Comment by waynecz** [comment]
组件暂时还不支持哦，要做的话可以在 `onChange` 事件中完成

**Comment by KsssAlleria** [comment]
onChange 参数 并没有文件的路径？ 怎么办

**Comment by waynecz** [comment]
@KsssAlleria web 为了安全是不能获取文件具体路径的
