### ISSUE TITLE
朋友你好，动态添加imgInputer , 删除后渲染有问题

### ISSUE THREAD

**Issue by yukiflandre** [waynecz/vue-img-inputer#32]
#关键代码：
```vue
<div v-for="(item,index) in fileList">
      <imgInputer v-model="item.file" accept="image/*" @onChange="fileChange"/>
      <button type="button" @click="remove(fileList,index)">remove</button>
</div>
<button type="button" @click="add">add</button>


   methods: {
      fileChange(file, name) {
        console.log('File:', file);
        console.log('FileName:', name);
     },
      add(){
        this.fileList.push({
          file:null
        })
      },
      remove(item,index){
        item.splice(index,1)
      }
    }
```
描述：
当我执行add()方法后，fileList = [{file:null},{file:null}]，添加图片以后fileList = [{file:file1},{file:file2}]，如果执行remove()删除file1,数据正常删除，但是页面上没有实时渲染

**Comment by waynecz** [comment]
试下
1.
```js
this.$delete(this.item, index)
```

2.
```js
this.$nextTick(() => { item.splice(index,1) })
```

**Comment by yukiflandre** [comment]
不得行
我试了下Vue.$set,，也不行...

**Comment by yukiflandre** [comment]
找到原因了
和https://segmentfault.com/q/1010000008975102这个问题一样

**Comment by yukiflandre** [comment]
利用:key解决

> 当 Vue.js 用 v-for 正在更新已渲染过的元素列表时，它默认用“就地复用”策略。如果数据项的顺序被改变，Vue 将不会移动 DOM 元素来匹配数据项的顺序， 而是简单复用此处每个元素，并且确保它在特定索引下显示已被渲染过的每个元素。这个类似 Vue 1.x 的 track-by="$index" 。

这个默认的模式是高效的，但是只适用于不依赖子组件状态或临时 DOM 状态 (例如：表单输入值) 的列表渲染输出。

为了给 Vue 一个提示，以便它能跟踪每个节点的身份，从而重用和重新排序现有元素，你需要为每项提供一个唯一 key 属性。理想的 key 值是每项都有的且唯一的 id。这个特殊的属性相当于 Vue 1.x 的 track-by ，但它的工作方式类似于一个属性，所以你需要用 v-bind 来绑定动态值 (在这里使用简写)：
