### ISSUE TITLE
安装一直报错

### ISSUE THREAD

**Issue by gaiai** [waynecz/vue-img-inputer#33]
无法安装，貌似node现在版本装不了？？？

<img width="563" alt="2017-10-09 3 30 10" src="https://user-images.githubusercontent.com/16616174/31320153-4b00224a-ac35-11e7-854b-84d1d6b55253.png">

**Comment by waynecz** [comment]
`node-sass`安装报错，你看下 node --version

**Comment by gaiai** [comment]
我本地node 是v6.11.4，demo没有问题，引入npm install vue-img-inputer -D 就不行。
