### ISSUE TITLE
chrome点击上传打开弹窗大概要10s

### ISSUE THREAD

**Issue by longting** [waynecz/vue-img-inputer#40]
chrome点击上传打开弹窗大概要10s， 在iview里面使用并且报错
··
Property or method "back" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components
··
··
[Vue warn]: Invalid handler for event "click": got undefined
··

**Comment by longting** [comment]
慢的原因是type限制的原因，但是报错是什么什么原因？？

**Comment by waynecz** [comment]
back 这个方法不是组件里的，应该是其他地方报错啦

慢可能是因为 accept 没指定，设定下 accept 为具体的类型可能可以解决
![image](https://user-images.githubusercontent.com/11238540/35029625-c687f6ee-fb96-11e7-8201-85d2673f7144.png)
