### ISSUE TITLE
我想问问 这个demo down下来后 怎么使用？

### ISSUE THREAD

**Issue by wqwangruiqi** [waynecz/vue-img-inputer#42]
我目前是 直接 进入文件加 执行 npm start 报错

**Comment by wqwangruiqi** [comment]
我准备在移动端使用这个插件 上传多张图片 可调用相机和文件夹 可以吗？

**Comment by waynecz** [comment]
暂不支持上传多张图片哦，目前移动端调用相机和文件夹不能一起拥有，有点 Bug，所以暂时不建议在移动端使用，改天修一下

**Comment by jiaoguoliang** [comment]
cnpm install 加载依赖，然后启动项目即可
