### ISSUE TITLE
传入的图片不会自动显示完整

### ISSUE THREAD

**Issue by Mr-Qiao** [waynecz/vue-img-inputer#45]

**Comment by Mr-Qiao** [comment]
不是 就是点击上传的那个框  选择图片后 图片显示在这个框中 不会自适应 图片只会显示框的大小  多出来的部分就不显示了

**Comment by waynecz** [comment]
这个是为了防止破坏页面布局，如果随图片比例更改宽高的话可能造成整个页面重排了
