### ISSUE TITLE
移动端无法打开相册，总是默认打开摄像头

### ISSUE THREAD

**Issue by Yuanwei1992** [waynecz/vue-img-inputer#46]
设置accept="image/*" ，移动端无法同时打开拍照、相册，永远默认直接打开摄像头，capture 属性设置无效。想打开相册不行。iOS 安卓都不行

**Comment by waynecz** [comment]
这两天修复

**Comment by waynecz** [comment]
v2.0.0 修复了，可以试试

**Comment by Yuanwei1992** [comment]
更新到2.0了  移动端还是直接打开的摄像头，没有打开相册 。无法选照片。capture 默认是false的话 应该是不打开摄像头的，capture这个好像没有用

**Comment by Yuanwei1992** [comment]
ok 了  ，是可以的
