### ISSUE TITLE
多个图片上传支持吗

### ISSUE THREAD

**Issue by lifangling** [waynecz/vue-img-inputer#47]
请问上传一个照片之后，可以出现一个新的选择图片的地方，支持上传多涨图片吗

**Comment by lifangling** [comment]
支持删除操作吗，大大

**Comment by waynecz** [comment]
+ 正在写 2.0 ，已经确定不支持多图片了，多图片就得多渲染几个组件😋
+ 删除的场景可以说一下吗？
