### ISSUE TITLE
如何上传图片

### ISSUE THREAD

**Issue by hellovue** [waynecz/vue-img-inputer#5]
组件装好了，组件上有个v-model属性，我该怎么连同表单一起上传文件呢？

**Comment by waynecz** [comment]
@hellovue 要随同其他表单字段一起的话
首先
```js
let postData = new FormData()
postData.append('pic', this.pic) // 绑定的图片值
postData.append('otherValue', this.otherValue) // 其他表单值

POST(URL, postData)
```

也要注意请求的`Content-Type`需要是`Multipart/form-data`

**Comment by hellovue** [comment]
@waynecz this.pic 的数据格式是什么啊，我想把图片用base64转成字符串  在数据库中我保存这个字符串就可以了

**Comment by hellovue** [comment]
@waynecz 你的this.pic难道就是组件上面的v-model?

**Comment by waynecz** [comment]
@hellovue 嗯，默认v-model绑定的是file类型的数据，如果你要转成base64可以在请求之前转化一次，然后用JSON的形式或者其他都可以了

**Comment by hellovue** [comment]
@waynecz 怎么转，利用FileReader转？

**Comment by hellovue** [comment]
@waynecz 感觉要接近真相了

**Comment by hellovue** [comment]
@waynecz  var reader = new FileReader();
                // 将图片将转成 base64 格式
                reader.readAsText(that.activityBaseInfo.picValue);
                // 读取成功后的回调
                let dsadsa = '';
                reader.onloadend = function (e) {
                    dsadsa = e.target.result;
                }

**Comment by hellovue** [comment]
@waynecz 这是我用测试用的，不过不行啊

**Comment by waynecz** [comment]
@hellovue 利用FileReader的话要注意onloadend这是个回调，所以请求要写在onloadend的回调里，例：
```js
// 假设this.pic为v-model绑定值
let reader = new FileReader()
reader.readAsDataURL(this.pic)

reader.onloadend = function () {
    let base64 = this.result // 注意这里的this不是指当前组件实例了
    let postData = {
       file: base64 
   }
   POST(URL, postData)
}

```

你试试这样行不行

**Comment by hellovue** [comment]
@waynecz let base64 = this.result // 注意这里的this不是指当前组件实例了   你这里面的this.result 已经是base64转换过的字符串？怎么感觉不对啊

**Comment by waynecz** [comment]
@hellovue 这里的this指的是那个reader，reader.result就已经是转化过的base64了。

**Comment by hellovue** [comment]
@waynecz 恩恩，好的我去试试

**Comment by nevermind123456** [comment]
请问一下，v-model的值在哪里呢，就是前面看到的this.pic请问在哪里设置的呢？好像没有看到。

**Comment by waynecz** [comment]
@nevermind123456 
```vue

<template>
    <vue-img-inputer v-model="pic" />
</template>

<script>
export default {
    data() {
        return {
            pic: null
        }
    }
}
</script>

```

这样子，绑定 pic 到组件上

**Comment by vxhly** [comment]
let reader = new FileReader()
reader.readAsDataURL(this.pic)

reader.onloadend = function () {
    let base64 = this.result // 注意这里的this不是指当前组件实例了
    let postData = {
       file: base64 
   }
   POST(URL, postData)
}
这样写根本就不能将数据post出去

**Comment by vxhly** [comment]
@waynecz 如果没有选择任何文件，然后就上传了，会报错，怎么解决
![qq 20170904164223](https://user-images.githubusercontent.com/17906558/30018650-3f985bee-9190-11e7-893b-7fec7109d9e6.png)
