### ISSUE TITLE
文档的 uoload... 让我找了1一小时

### ISSUE THREAD

**Issue by zhpefe** [waynecz/vue-img-inputer#50]

**Comment by waynecz** [comment]
噗！！骚瑞。😅 你觉得有什么办法可以解决这个问题吗

**Comment by zhpefe** [comment]
噗，看看你API文档的这里，我复制的。。：`
API
Auto upload related
auto-uoload: Boolean
set to enable auto-upload`

**Comment by waynecz** [comment]
@zhpefe  看到的难道不是这样的？
![image](https://user-images.githubusercontent.com/11238540/42927048-cf317626-8b65-11e8-8903-f48ef48817d4.png)
