### ISSUE TITLE
关于reset 的使用，根本不知道使用方法是什么？

### ISSUE THREAD

**Issue by biaohua** [waynecz/vue-img-inputer#52]
this.$refs.XXX.reset()
这个用不了

**Comment by waynecz** [comment]
可以展示下代码吗，我测试是没问题的

**Comment by biaohua** [comment]
例如：
<vue-img-inputer size="large" ref="imgUpload"></vue-img-inputer>
父级调用：this.$refs.imgUpload.reset()
报错：reset is undefined

**Comment by biaohua** [comment]
在吗？可以给一下你的使用代码不？

**Comment by waynecz** [comment]
😅....不是应该你贴下你的代码吗

```vue
<template>
  ...
  <img-inputer ref="imgUpload" />
  ...
</template>

<script>
  ...
  someMethod() {
    this.$refs.imgUpload.reset()
  }
  ...
</script>
```

**Comment by biaohua** [comment]
<vue-img-inputer @onChange="uploadLicenseImage" ref="imgUpload"></vue-img-inputer>
someMethod () {
      this.$refs.imgUpload.reset()
}
![qq20180907-155950](https://user-images.githubusercontent.com/18567038/45206290-3c95a700-b2b7-11e8-8b5b-6bffe74b9fcc.jpg)

**Comment by waynecz** [comment]
emm 组件的版本和 vue 版本提供一下？

**Comment by biaohua** [comment]
`"vue": "^2.5.13",
 "vue-area-linkage": "^1.2.5",
 "vue-axios": "^2.0.2",
 "vue-clipboard2": "0.0.8",
 "vue-highcharts": "0.0.10",
 "vue-i18n": "^7.3.0",
 "vue-moment": "^3.0.0",
 "vue-router": "^2.3.1",
 "vuelidate": "^0.6.1",
 "vuex": "^2.4.0"

 "vue-img-inputer": "^1.1.5"`

**Comment by waynecz** [comment]
组件版本太低了， `npm i vue-img-inputer@2`

**Comment by waynecz** [comment]
提个小小的建议哦，建议代码用代码块包裹

例如：
```markdown
```vue
<vue-img-inputer @onchange="uploadLicenseImage" ref="imgUpload">

someMethod () {
  this.$refs.imgUpload.reset()
}
```
```

另外在 issue 最开始尽可能的提供一些必要的信息（自己的代码、插件版本、开发环境等），这样对开发者将带来巨大的帮助😃

**Comment by biaohua** [comment]
好的，谢谢。下次我会注意
