### ISSUE TITLE
建议加上一个type，并且在onchange事件里面可以取到此type

### ISSUE THREAD

**Issue by xiaoweiQ** [waynecz/vue-img-inputer#54]
兄弟你好，我现在要做多张图片上传功能，比如身份证或者是行驶证，或者是些其他的证件，我需要将这些不同的type传给后端，我建议在props里面可以支持从外界传入一个type，并且在onchange事件里面可以让我取到这个type

**Comment by waynecz** [comment]
请问你是用 autoupload 的吗？
如果启用autoupload 有一个 extra-data 可配置
![image](https://user-images.githubusercontent.com/11238540/47979852-172ee900-e100-11e8-8031-534b15fb2d3c.png)
