### ISSUE TITLE
Use vue-cli3 typescript issues

### ISSUE THREAD

**Issue by t496971418** [waynecz/vue-img-inputer#58]
when i use typescript in vue-cli3.0,
i try `import 'vue-img-inputer/dist/index.css'`
npm show 
`./node_modules/vue-img-inputer/dist/fonts/iconfont.svg?t=1487650731256
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.`
how to fix this issues
i try to modify my vue.config.js, add svg's url-loader and file-loader, but it still doesn't work.

**Comment by t496971418** [comment]
when i use svg-sprite-loader ,it can't work, is this this problem with svg-sprite-loader?
do you know how to fix it

**Comment by t496971418** [comment]
I not know why `svg-sprite-loader` disable resolve `dist/fonts/iconfont.svg`
but `file-loader` can read this file
maybe both of loader can't mix

**Comment by waynecz** [comment]
sorry about to see this issue late😂, and you, big brother, figured it out, GJ!
