### ISSUE TITLE
在ios上直接打开相机，不能从相册中选择图片，怎么才能解决啊

### ISSUE THREAD

**Issue by leeycode** [waynecz/vue-img-inputer#6]

**Comment by waynecz** [comment]
@leeycode 是指可以直接打开相机，但是不能选择照片是吗？
可以把你`ios版本`和`运行环境`(微信 || Safari || others)以及`用得代码`贴一下吗？

**Comment by leeycode** [comment]
```
          <div class="avatar f-pa" v-bind:style="{background: 'url(' + userInfo.avatar + ')'}">
            <VueImgInputer v-model="picValue" theme="light" size="small" placeholder="" accept="image" icon="false">
            </VueImgInputer>
          </div>
```
以上是在组件中使用的代码，我是局部导入的，测试用了ipone5和iPhone6 10.3,点击的时候直接打开了相机，不能从相册中选择照片。

**Comment by waynecz** [comment]
@leeycode 
```html
<VueImgInputer accept="image"></VueImgInputer>
```
这里的accept的值需要写成`image/*`或者什么都不写，这样默认会是`image/*,video/*;`

你试一下这个修改卡能不能解决

**Comment by leeycode** [comment]
@waynecz 还是没能解决呢，我加了image/*，还是不能打开相册

**Comment by leeycode** [comment]
@waynecz 我有注意到你的在线demo，在iphone的浏览器中也不能打开相册

**Comment by waynecz** [comment]
@leeycode 抱歉前两天没及时回复。
我看了下可能是组件里capture="vedio"这个属性导致的，因为我手头暂时没有iphone可以测试，所以你可以下载下代码去掉capture这个属性然后测试下吗？或者我暂时加个capture的prop

**Comment by leeycode** [comment]
非常感谢，我在源码里面删掉capture="vedio"，问题得到解决

**Comment by waynecz** [comment]
属性已修改，版本1.0.7
```html
<VueImgInputer :capture="false"></VueImgInputer>
```
即可

十分感谢你的反馈！！
