### ISSUE TITLE
Replace maxSize translate

### ISSUE THREAD

**Issue by mgarcia96** [waynecz/vue-img-inputer#60]
Hey, the text of the size is not translated:

```javascript
handleFileChange: function handleFileChange(e) {
        if (typeof e.target === "undefined") this.file = e[0];else this.file = e.target.files[0];
        this.errText = "";
        var size = Math.floor(this.file.size / 1024);

        if (size > this.maxSize) {
          this.errText = "\u6587\u4EF6\u5927\u5C0F\u4E0D\u80FD\u8D85\u8FC7".concat(this.sizeHumanRead);
          return false;
        } // 双向绑定
}
```

**Comment by mgarcia96** [comment]
> Thanks for reporting! I will add simple i18n for the component.
> 
> Resolve in [v2.1.1](https://github.com/waynecz/vue-img-inputer/commit/b82ba9fe2338493c330f60ad8b37a16d942bdb74)

Perfect thanks! Can you please update the Docs?

**Comment by mgarcia96** [comment]
You can put these translates like the others in the Input attribute? I have to change the language for spanish

**Comment by waynecz** [comment]
@mgarcia96 sorry about late, hope not troubled your development, Props inserted in [v2.1.2](https://www.npmjs.com/package/vue-img-inputer/v/2.1.2) 

document in README:
![image](https://user-images.githubusercontent.com/11238540/51450424-acd72d80-1d6b-11e9-8809-985747093bc0.png)
