### ISSUE TITLE
Release v2.1.4 without dist folder through npm

### ISSUE THREAD

**Issue by felipeozalmeida** [waynecz/vue-img-inputer#65]
**Operating system**

elementary Juno 5 (based on Ubuntu 18.04)

**Project**

Bootstrapped with Vue CLI 3

**Package manager**

Yarn v1.17.3

**Issue**

As of today, doing `yarn add vue-img-inputer` installs the v2.1.4 of the package without its dist folder, not compiling.

The version prior to that (v2.1.3), e.g. `yarn add vue-img-inputer@2.1.3`, comes with the dist folder as expected.

Maybe a review of the published package should solve the issue.

**Comment by waynecz** [comment]
Thanks for the feedback, now fixed, fix version: 2.1.6
