### ISSUE TITLE
引入组件时总报 请选择正确类型的文件

### ISSUE THREAD

**Issue by kevinlee22** [waynecz/vue-img-inputer#7]
请问这几个demo的源码有嘛

**Comment by waynecz** [comment]
可以贴下你的代码和运行的环境吗？

DEMO源码的之前不小心被我删了没有备份😂

**Comment by kevinlee22** [comment]
<VueImgInputer
            v-model="picValue"
            theme="light"
            name="pic"
            size="small">
        </VueImgInputer>
我是引入组件直接这么使用的，我需求也只是想在表单中预览一下上传的图片，发送给服务器是其他的按钮控制，这个需求这么写代码对嘛

**Comment by kevinlee22** [comment]
完美解决，感谢
