### ISSUE TITLE
拖拽上传无法获取文件名

### ISSUE THREAD

**Issue by sinchang** [waynecz/vue-img-inputer#9]
在 [demo](http://waynecz.github.io/VueImgInputer/index.html) 上测试：

- 使用点击上传
```
document.getElementById('wddvm').value
"C:\fakepath\lifecycle.png"
```
- 拖拽上传
```
document.getElementById('8h5cb').value
"" // 返回空
```
另外建议把 demo 的源码也传到 GitHub，便于他人 pr 时调试。

**Comment by waynecz** [comment]
回复晚了不好意思，谢谢指出问题，我把demo源码去补上，另外> 拖拽上传无法获取文件名  的问题也会解决下。

还有就是文件名可以通过`v-model` 绑定的值的`name`属性获得
```html
<vueImgInputer v-model="file"  :onChange="fileChange" />

<sctipt>
...
fileChange (file, fakePath) {
  console.log(file.name)
}
...
</script>
```

**Comment by sinchang** [comment]
好的，感谢。@waynecz

**Comment by waynecz** [comment]
项目升级了下，可以直接在项目里更改查看demo，直接改组件了 @sinchang
